package org.bukkit;
public enum Material {
    AIR, STONE, COBBLESTONE, BEDROCK, WATER, LAVA, CHEST, TNT, COBWEB, STRING,
    TRIPWIRE_HOOK, MAGMA_BLOCK, CACTUS, SOUL_SAND, IRON_PICKAXE, NETHERITE_PICKAXE,
    DIAMOND_PICKAXE, IRON_SWORD, STONE_SWORD, IRON_AXE, BOW, ARROW, SHIELD, COMPASS,
    BLAZE_ROD, GRAY_DYE, FISHING_ROD, SPYGLASS, AMETHYST_SHARD, PRISMARINE_SHARD,
    LAVA_BUCKET, MILK_BUCKET, WATER_BUCKET, FIRE_CHARGE, WIND_CHARGE, FLINT_AND_STEEL,
    POTION, ENCHANTED_GOLDEN_APPLE, GOLDEN_APPLE, COOKED_BEEF, OAK_PLANKS, OBSIDIAN,
    TUFF, POLISHED_TUFF, GLASS, SLIME_BLOCK, HONEY_BLOCK, RESIN_BLOCK, TERRACOTTA,
    POINTED_DRIPSTONE, CREAKING_HEART, REDSTONE_BLOCK, REDSTONE, REDSTONE_TORCH,
    REDSTONE_LAMP, REPEATER, PISTON, STICKY_PISTON, OBSERVER, COPPER_BULB,
    CRAFTER, DISPENSER, CRAFTING_TABLE, ENDER_PEARL, FEATHER, SCAFFOLDING,
    BREEZE_ROD, HEAVY_CORE, BUNDLE, CROSSBOW, OMINOUS_BOTTLE, GLASS_BOTTLE,
    GOLDEN_DANDELION, GOLDEN_CARROT, GOLD_NUGGET, NETHER_STAR, BARRIER,
    LIME_DYE, RED_DYE, WHITE_STAINED_GLASS_PANE, GLASS_PANE, STAINED_GLASS_PANE,
    LEATHER_HELMET, LEATHER_CHESTPLATE, LEATHER_LEGGINGS, LEATHER_BOOTS,
    CHAINMAIL_HELMET, CHAINMAIL_CHESTPLATE, CHAINMAIL_LEGGINGS, CHAINMAIL_BOOTS,
    IRON_HELMET, IRON_CHESTPLATE, IRON_LEGGINGS, IRON_BOOTS,
    COPPER_HELMET, NETHERITE_AXE, NETHERITE_SWORD, DIAMOND_SWORD, DIAMOND_AXE,
    SNOWBALL, MACE, TRIAL_KEY, PAPER, STICK;
    public boolean isSolid(){return true;}
    public boolean isAir(){return this == AIR;}
    public static Material matchMaterial(String name){
        if (name == null) return null;
        try { return Material.valueOf(name.toUpperCase()); } catch (Exception e) { return null; }
    }
}
